### ISSUE TITLE
ASSERTION ERROR

### ISSUE THREAD

**Issue by nikhil666666** [next-security-lab/fakeVideoForensics#2]
I have followed the entire procedure as you have documented. But I am facing an assertion error when I am running it.
![WhatsApp Image 2020-06-02 at 2 18 23 PM](https://user-images.githubusercontent.com/43309606/83501414-b46d2180-a4dd-11ea-8062-c562f4dc129a.jpeg)

Please resolve the issue

**Comment by jiep** [comment]
Thanks for reporting this error!

We have updated the repo with a Dockerfile in order to simplify the installation. You only have to install [Docker](https://docs.docker.com/docker-for-windows) in your computer.

We hope this update solves your problem.

> Notice that GPU is not supported at this moment.
